exameNFL/core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path('create/team/', views.CreateTeam.as_view(), name="create_team"),
    path('list/team/', views.ListTeam.as_view(), name="list_team"),
    path('detail/team/<int:pk>/', views.DetailTeam.as_view(), name="detail_team"),
    path('update/team/<int:pk>/', views.UpdateTeam.as_view(), name="update_team"),
    path('delete/team/<int:pk>/', views.DeleteTeam.as_view(), name="delete_team"),

    path('create/stadium/', views.CreateStadium.as_view(), name="create_stadium"),
    path('list/stadium/', views.ListStadium.as_view(), name="list_stadium"),
    path('detail/stadium/<int:pk>/', views.DetailStadium.as_view(), name="detail_stadium"),
    path('update/stadium/<int:pk>/', views.UpdateStadium.as_view(), name="update_stadium"),
    path('delete/stadium/<int:pk>/', views.DeleteStadium.as_view(), name="delete_stadium"),

    path('create/city/', views.CreateCity.as_view(), name="create_city"),
    path('list/city/', views.ListCity.as_view(), name="list_city"),
    path('detail/city/<int:pk>/', views.DetailCity.as_view(), name="detail_city"),
    path('update/city/<int:pk>/', views.UpdateCity.as_view(), name="update_city"),
    path('delete/city/<int:pk>/', views.DeleteCity.as_view(), name="delete_city"),

    path('create/player/', views.PlayerCreate.as_view(), name="create_player"),
    path('list/player/', views.PlayerLIst.as_view(), name="list_player"),
    path('detail/player/<int:pk>/', views.PlayerDetail.as_view(), name="detail_player"),
    path('update/player/<int:pk>/', views.PlayerUpdate.as_view(), name="update_player"),
    path('delete/player/<int:pk>/', views.PlayerDelete.as_view(), name="delete_player"),

    path('create/owner/', views.OwnerCreate.as_view(), name="create_owner"),
    path('list/owner/', views.OwnerList.as_view(), name="list_owner"),
    path('detail/owner/<int:pk>/', views.OwnerDetail.as_view(), name="detail_owner"),
    path('update/owner/<int:pk>/', views.OwnerUpdate.as_view(), name="update_owner"),
    path('delete/owner/<int:pk>/', views.OwnerDelte.as_view(), name="delete_owner"),

]

exameNFL/exameNFL/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
]

exameNFL/home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Prueba.as_view(), name="prueba"),
]

exameNFL/core/models.py
from django.db import models

# Create your models here.

class Team(models.Model):
    team_name = models.CharField(max_length=30, default="Nombre del equipo")
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.team_name


class Stadium(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    stadium_name = models.CharField(max_length=50, default="Nombre del estadio")
    capacity = models.FloatField()

    def __str__(self):
        return self.stadium_name

class City(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    city_name = models.CharField(max_length=20, default="Nombre de la ciudad")

    def __str__(self):
        return self.city_name

class Players(models.Model):
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    number_player = models.FloatField()
    position = models.CharField(max_length=50)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class Owner(models.Model):
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

exameNFL/core/forms.py
from django import forms

from .models import *

# T E A M
class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = [
            "team_name",
        ]
        widgets = {
            "team_name": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
        }

#-----------------------------------------------------------------------------------------------------------------#

# S T A D I U M
class StadiumForm(forms.ModelForm):
    class Meta:
        model = Stadium
        fields = [
            "stadium_name",
            "team",
        ]
        widgets = {
            "stadium_name": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
            "team": forms.Select(attrs={"type":"select", "class":"form-control"})
        }

# ------------------------------------------------------------------------------------------------------------------#

# C I T Y
class CityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = [
            "city_name",
            "team",
        ]
        widgets = {
            "city_name": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
            "team": forms.Select(attrs={"type":"select", "class":"form-control"})
        }

# P L A Y E R S
class PlayerForm(forms.ModelForm):
    class Meta:
        model = Players
        fields = [
            "name",
            "last_name",
            "team",
        ]
        widgets = {
            "name": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
            "last_name": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
            "team": forms.Select(attrs={"type":"select", "class":"form-control"})
        }

# O W N E R S
class OwnerForm(forms.ModelForm):
    class Meta:
        model = Owner
        fields = [
            "name",
            "last_name",
            "team",
        ]
        widgets = {
            "name": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
            "last_name": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
            "team": forms.Select(attrs={"type":"select", "class":"form-control"})
        }

exameNFL/core/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.views import generic

from .models import *
from .forms import *

# Create your views here.

### T E A M ###
  
# list
class ListTeam(generic.View):
    template_name = "core/team/list_team.html"
    context = {}

    def get(self, request, *args, **kwargs):
        #lleva s
        teams = Team.objects.all()
        self.context = {
            "teams": teams
        }
        return render(request, self.template_name, self.context)

# detail
class DetailTeam(generic.View):
    template_name = "core/team/detail_team.html"
    context = {}

    def get(self, request, pk, *args, **kargs):
        #no lleva s
        team = Team.objects.get(pk=pk)
        self.context = {
            "team": team
        }
        return render(request, self.template_name, self.context)

# create
class CreateTeam(generic.CreateView):
    template_name = "core/team/create_team.html"
    context = {}
    form_class = TeamForm
    success_url = reverse_lazy("core:list_team")

# update
class UpdateTeam(generic.UpdateView):
    template_name = "core/team/update_team.html"
    model = Team
    form_class = TeamForm
    success_url = reverse_lazy("core:list_team")

# delete
class DeleteTeam(generic.DeleteView):
    template_name = "core/team/delete_team.html"
    model = Team
    success_url = reverse_lazy("core:list_team")

#-------------------------------------------------------------------------#

### S T A D I U M ###
class ListStadium(generic.View):
    template_name = "core/stadium/list_stadium.html"
    context = {}

    def get(self, request, *args, **kwargs):
        stadiums = Stadium.objects.all()
        self.context = {
            "stadiums": stadiums
        }
        return render(request, self.template_name, self.context)

# detail
class DetailStadium(generic.View):
    template_name = "core/stadium/detail_stadium.html"
    context = {}

    def get(self, request, pk, *args, **kargs):
        #no lleva s
        stadium = Stadium.objects.get(pk=pk)
        self.context = {
            "stadium": stadium
        }
        return render(request, self.template_name, self.context)

# create
class CreateStadium(generic.CreateView):
    template_name = "core/stadium/create_stadium.html"
    context = {}
    form_class = StadiumForm
    success_url = reverse_lazy("core:list_stadium")

# update
class UpdateStadium(generic.UpdateView):
    template_name = "core/stadium/update_stadium.html"
    model = Stadium
    form_class = StadiumForm
    success_url = reverse_lazy("core:list_stadium")

# delete
class DeleteStadium(generic.DeleteView):
    template_name = "core/stadium/delete_stadium.html"
    model = Stadium
    success_url = reverse_lazy("core:list_stadium")

#-------------------------------------------------------------------------#

### C I T Y ###

# list
class ListCity(generic.View):
    template_name = "core/city/list_city.html"
    context = {}

    def get(self, request, *args, **kwargs):
        #lleva s
        citys = City.objects.all()
        self.context = {
            "citys": citys
        }
        return render(request, self.template_name, self.context)

class DetailCity(generic.View):
    template_name = "core/city/detail_city.html"
    context = {}

    def get(self, request, pk, *args, **kargs):
        city = City.objects.get(pk=pk)
        self.context = {
            "city": city
        }
        return render(request, self.template_name, self.context)

# create
class CreateCity(generic.CreateView):
    template_name = "core/city/create_city.html"
    context = {}
    form_class = CityForm
    success_url = reverse_lazy("core:list_city")

# update
class UpdateCity(generic.UpdateView):
    template_name = "core/city/update_city.html"
    model = City
    form_class = CityForm
    success_url = reverse_lazy("core:list_city")

# delete
class DeleteCity(generic.DeleteView):
    template_name = "core/city/delete_city.html"
    model = City
    success_url = reverse_lazy("core:list_city")

### P L A Y E R S ###

# list
class PlayerLIst(generic.View):
    template_name = "core/players/list_player.html"
    context = {}

    def get(self, request, pk, *args, **kwargs):
        players = Players.objects.filter(team__id=pk)
        player = Players.objects.all()
        self.context = {
            "player": player,
            "players": players
        }
        return render(request, self.template_name, self.context)

class PlayerDetail(generic.View):
    template_name = "core/players/detail_player.html"
    context = {}

    def get(self, request, pk, *args, **kargs):
        player = Players.objects.get(pk=pk)
        self.context = {
            "player": player
        }
        return render(request, self.template_name, self.context)

# create
class PlayerCreate(generic.CreateView):
    template_name = "core/players/create_player.html"
    context = {}
    form_class = PlayerForm
    success_url = reverse_lazy("core:list_player")

# update
class PlayerUpdate(generic.UpdateView):
    template_name = "core/players/update_player.html"
    model = Players
    form_class = PlayerForm
    success_url = reverse_lazy("core:list_player")

# delete
class PlayerDelete(generic.DeleteView):
    template_name = "core/players/delete_player.html"
    model = Players
    success_url = reverse_lazy("core:list_player")

### O W N E R S ###

# list
class OwnerList(generic.View):
    template_name = "core/owner/list_owner.html"
    context = {}

    def get(self, request, pk, *args, **kwargs):
        #lleva s
        owner = Owner.objects.all()
        owner2 = Owner.objects.get(id=pk)
        team = Team.objects.get(owner__id=pk)
        stadium = Stadium.objects.get(team__id=team.id)
        self.context = {
            "owner": owner,
            "owner2": owner2,
            "team":team,
            "stadium":stadium

        }
        return render(request, self.template_name, self.context)

class OwnerDetail(generic.View):
    template_name = "core/owner/detail_owner.html"
    context = {}

    def get(self, request, pk, *args, **kargs):
        owner = Owner.objects.get(pk=pk)
        self.context = {
            "owner": owner
        }
        return render(request, self.template_name, self.context)

# create
class OwnerCreate(generic.CreateView):
    template_name = "core/owner/create_owner.html"
    context = {}
    form_class = OwnerForm
    success_url = reverse_lazy("core:list_owner")

# update
class OwnerUpdate(generic.UpdateView):
    template_name = "core/owner/update_owner.html"
    model = Owner
    form_class = OwnerForm
    success_url = reverse_lazy("core:list_owner")

# delete
class OwnerDelte(generic.DeleteView):
    template_name = "core/owner/delete_owner.html"
    model = Owner
    success_url = reverse_lazy("core:list_owner")

exameNFL/templates/core/stadium/create_stadium.html
{% block title %}
CREATE STADIUM VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success form-control">Create Stadium</button>
        <a href="{% url 'core:list_stadium' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

exameNFL/templates/core/stadium/delete_stadium.html
{% block title %}
    DELETE STADIUM VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="card border-danger mb-3" style="max-width: 20rem;">
            <div class="card-header">Header</div>
            <div class="card-body">
              <h4 class="card-title">Danger card title</h4>
              <p><h1>¿Realmente deseas eliminar este estadio: {{ object.stadium_name }}?</h1></p>
            </div>
          </div>
        <button type="" class="btn btn-outline-danger">Delete Stadium</button>
        <a href="{% url 'core:list_stadium' %}"></a>
    </form>
{% endblock content %}

exameNFL/templates/core/stadium/detail_stadium.html
{% block title %}
    STADIUM DETAIL VIEW
{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ stadium }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the Stadium: {{ stadium.stadium_name }}</strong> <!-- It is supervisor: {{ team.supervisor }} <br> -->
          <!-- timestamp: {{ product.timestamp }} --- category: {{ product.subcategory }} -->
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <!-- <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Brand: {{ product.brand }}
        </button> -->
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <!-- <strong>This is the Status: {{ product.status }}</strong><br>
          Stock: {{ product.stock }} -->
          <!-- <br> -->
          <a href="{% url 'core:list_stadium' %}" class="btn">Back To List</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

exameNFL/templates/core/stadium/list_stadium.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LIST STADIUM</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
  <div class="container">
        <div class="row">
            <div class="col">
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="#">NFL</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home:prueba' %}">Home</a>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Teams
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'core:list_team' %}">List of Teams</a></li>
                            </ul>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Stadiums
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'core:list_stadium' %}">List of Stadiums</a></li>
                            </ul>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Citys
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'core:list_city' %}">List Citys</a></li>
                            </ul>
                          </li>
                        </ul>
                        <form class="d-flex" role="search">
                          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                          <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                        </div>
                    </div>
                </nav>
            </div>        
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <a href="{% url 'core:create_stadium' %}" class="btn btn-outline-success">Add a Stadium</a>
    <br><br>
    <table class="table table-striped table-hover">
        <thead>
            <th>ID</th>
            <th>STADIUM NAME</th>
            <th>TEAM</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for stadium in stadiums %}
                <tr>
                    <td>{{ stadium.id }}</td>
                    <td>{{ stadium.stadium_name }}</td>
                    <td>{{ stadium.team }}</td>
                    <td><a href="{% url 'core:detail_stadium' stadium.id %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'core:update_stadium' stadium.id %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_stadium' stadium.id %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

exameNFL/templates/core/stadium/update_stadium.html
{% block title %}
    <title>UPDATE STADIUM VIEW</title>
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary form-control">Update Stadium</button>
        <br>
        <a href="{% url 'core:list_stadium' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}