exameNFL/core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path('create/team/', views.CreateTeam.as_view(), name="create_team"),
    path('list/team/', views.ListTeam.as_view(), name="list_team"),
    path('detail/team/<int:pk>/', views.DetailTeam.as_view(), name="detail_team"),
    path('update/team/<int:pk>/', views.UpdateTeam.as_view(), name="update_team"),
    path('delete/team/<int:pk>/', views.DeleteTeam.as_view(), name="delete_team"),

    path('create/stadium/', views.CreateStadium.as_view(), name="create_stadium"),
    path('list/stadium/', views.ListStadium.as_view(), name="list_stadium"),
    path('detail/stadium/<int:pk>/', views.DetailStadium.as_view(), name="detail_stadium"),
    path('update/stadium/<int:pk>/', views.UpdateStadium.as_view(), name="update_stadium"),
    path('delete/stadium/<int:pk>/', views.DeleteStadium.as_view(), name="delete_stadium"),

    path('create/city/', views.CreateCity.as_view(), name="create_city"),
    path('list/city/', views.ListCity.as_view(), name="list_city"),
    path('detail/city/<int:pk>/', views.DetailCity.as_view(), name="detail_city"),
    path('update/city/<int:pk>/', views.UpdateCity.as_view(), name="update_city"),
    path('delete/city/<int:pk>/', views.DeleteCity.as_view(), name="delete_city"),

    path('create/player/', views.PlayerCreate.as_view(), name="create_player"),
    path('list/player/', views.PlayerLIst.as_view(), name="list_player"),
    path('detail/player/<int:pk>/', views.PlayerDetail.as_view(), name="detail_player"),
    path('update/player/<int:pk>/', views.PlayerUpdate.as_view(), name="update_player"),
    path('delete/player/<int:pk>/', views.PlayerDelete.as_view(), name="delete_player"),

    path('create/owner/', views.OwnerCreate.as_view(), name="create_owner"),
    path('list/owner/', views.OwnerList.as_view(), name="list_owner"),
    path('detail/owner/<int:pk>/', views.OwnerDetail.as_view(), name="detail_owner"),
    path('update/owner/<int:pk>/', views.OwnerUpdate.as_view(), name="update_owner"),
    path('delete/owner/<int:pk>/', views.OwnerDelte.as_view(), name="delete_owner"),

]

exameNFL/exameNFL/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
]

exameNFL/home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Prueba.as_view(), name="prueba"),
]

exameNFL/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
  <div class="container">
        <div class="row">
            <div class="col">
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="#">NFL</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home:prueba' %}">Home</a>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Teams
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'core:create_team' %}">New Team</a></li>
                              <li><a class="dropdown-item" href="{% url 'core:list_team' %}">List of Teams</a></li>
                              <li><hr class="dropdown-divider"></li>
                            </ul>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Stadiums
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'core:create_stadium' %}">New Stadium</a></li>
                              <li><a class="dropdown-item" href="{% url 'core:list_stadium' %}">List of Stadiums</a></li>
                              <li><hr class="dropdown-divider"></li>
                            </ul>
                          </li>

                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Players
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'core:create_player' %}">New Player</a></li>
                              <li><a class="dropdown-item" href="{% url 'core:list_player' %}">List of Players</a></li>
                              <li><hr class="dropdown-divider"></li>
                            </ul>
                          </li>

                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Owners
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'core:create_owner' %}">New Owner</a></li>
                              <li><a class="dropdown-item" href="{% url 'core:list_owner' %}">List of Owner</a></li>
                              <li><hr class="dropdown-divider"></li>
                            </ul>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Citys
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'core:list_city' %}">List Citys</a></li>
                            </ul>
                          </li>
                        </div>
                    </div>
                </nav>
            </div>    
            <div class="col">
              {% block content %}
              {% endblock content %}
            </div>    
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>